source/layouts/layout.erb
source/stylesheets/screen.css.scss

Add custom styles

---

source/includes/reference/_recipients.md

Added documentation for uniqueIdLookup

added documentation for /uniqueIdLookup

---

source/includes/reference/_recipients.md

Changed formatting for uniqueIdLookup from POST to GET

changed formatting from POST to GET

---

source/includes/_usecases.md

Remove rev share

---

source/includes/reference/_language.md
source/index.html.md

Add laguage support info

---

source/includes/_banks.md
source/includes/_usecases.md

Added more detail to bank guide. More to come but this is enough for a first review I think

Add more detail to banks guide

---

source/includes/_banks.md

fix bank guide typos and formatting

---

source/includes/reference/_recipients.md

MEA-808: Renamed ghana to ghana_local account type

---

.gitignore
README.md
source/includes/_banks.md
source/includes/reference/_profiles.md

Describing director, ubos and update-window APIs

BP-105 Adding docs for new business APIs

---

source/includes/reference/_language.md

Updated information about language support for all /transfers endpoints

BP-95: Update info on transfers language support

---

source/includes/_banks.md
source/includes/_contact-us.md
source/includes/_payouts.md

Add status page.

---

source/includes/reference/webhooks.md

These examples should make it more obvious to developers what is required.

Add more details and examples on what a valid webhook URL looks like

---

source/includes/_banks.md

Improve auth info for banks

---

source/includes/reference/_recipients.md

Adding Interac recipient creation documentation.

Adding Interac recipient creation doc for API

---

source/includes/_banks.md
source/includes/_contact-us.md
source/includes/_payouts.md
source/includes/_third-party-payouts.md
source/includes/reference/_profiles.md

New option field for onboarding a business - allows automated biz verification

Biz profile category

---

source/includes/reference/_profiles.md

Updating docs to add social security number when to documents users can send

BP-232: adding social security number

---

source/includes/reference/_profiles.md
source/includes/reference/_users.md

Add Biz categories

---

source/includes/_banks.md
source/includes/_connected-apps.md

Authorization page params as table

---

source/includes/_payouts.md
source/includes/reference/_borderless.md

Update documentation for GET statements endpoint to V3

---

source/includes/reference/_app_webhooks.md
source/includes/reference/_profile_webhooks.md
source/includes/reference/_webhook_events.md
source/includes/reference/_webhooks.md
source/index.html.md

include new webhooks in index

---

source/includes/_payouts.md
source/includes/reference/_transfers.md

Update documentation for POST transfer payments endpoint to V3

---

source/includes/reference/_webhook_events.md

Webhook event amends

---

source/includes/reference/_profile_webhooks.md

Add webhooks UI link

---

source/includes/_openbanking.md

Point MTLS link to the relevant RFC instead of wikipedia
Clarify which OB certificate types are we accepting

Open Banking changes after review

---

source/includes/reference/_app_webhooks.md
source/includes/reference/_profile_webhooks.md
source/includes/reference/_webhook_events.md
source/includes/reference/_webhooks_v1.md
source/index.html.md

Webhook docs updated

---

source/includes/reference/_app_webhooks.md

Docs for testing application webhooks.

Webhooks: test notifications API

---

source/layouts/layout.erb

https://transferwise.atlassian.net/wiki/spaces/C20/pages/1115621535/How+to+make+your+application+compliant+with+ICO+regulations

Display cookie consent banner and disable GA if user has not accepted

---

source/includes/_payouts.md

Update statements transacation types

---

source/includes/_affiliates.md
source/includes/_openbanking.md

Add Open Banking Prod Well Known Endpoint to Docs
Also, adjust the spacing between Open Banking and the previous Affiliates page because the code section is overlapping otherwise.

Add Open Banking Prod Well Known Endpoint to Docs

---

source/includes/_payouts.md

Added info about digital signatures, public keys API and strong customer authentication.
Should be merged only after the following changes are in place
https://github.com/transferwise/identity-service/pull/1081
https://github.com/transferwise/strong-customer-auth/pull/127
https://github.com/transferwise/rest-gateway/pull/1758

Added SCA workflow description

---

source/includes/_payouts.md

Update links to SCA section

---

source/includes/reference/_recipients.md

Adds link to Dynamic Forms UI for account requirements.

ADS-1354 Update account requirements docs

---

source/includes/_payouts.md

note about sca toggling in prod

---

source/includes/reference/_language.md
source/includes/reference/_quotes.md
source/includes/reference/_recipients.md

I have updated 3 files:
- quotes.md
- recipients.md
- language.md
I have fixed some typos, added some missing full stops for consistency and edited some markdown to fix line spacing.

JPC fixing typos

---

source/includes/_connected-apps.md
source/includes/_usecases.md
source/stylesheets/_variables.scss
source/stylesheets/screen.css.scss

Connected Apps guide refresh:
- Go into more detail about profile-specific linking
- Rework the text to make it more idiomatic English.
- Fixup links
- Tweak some CSS

Refresh Connected Apps integration guide

---

source/includes/_connected-apps.md

Mainly discussing verification status

"Working with profiles" Connected Apps guide section

---

source/includes/reference/_webhook_events.md

Fix mistakes and amend discussion of webhook events.

Fix mistakes and amend discussion of webhook events.

---

source/includes/reference/_recipients.md

Adding subversion for account-requirements

---

source/includes/_banks.md
source/includes/reference/_quotes.md

Adding feeDetails to v1 quotes to support partner fee.
Improved warning message for new docs version, people do not seem to read it.

Add v1 quote fee details

---

source/includes/reference/_webhook_events.md

- Rework "webhook event" discussion.
- Document new sha256-based signature header.

Update webhook documentation

---

source/includes/reference/_webhook_events.md

Webhook redux

---

source/includes/_payouts.md
source/includes/reference/_borderless.md

Adds the documentation for accounting statements downloading.

---

source/includes/_payouts.md

explain which countries are excluded from having to do sca

---

source/includes/_payouts.md

https://transferwise.atlassian.net/browse/EURO-2170
The EEA AUP page was moved to Lienzo

EURO-2170 - Update Acceptable Use Policy URL

---

source/includes/_payouts.md

Add new transfer flow diagram.
Add description for two statues.

Bs 426 Change transfer flow diagram

---

source/includes/_payouts.md

Update transfer state diagram. Change states description.

BS-426 Update transfer state diagram

---

source/includes/_banks.md
source/includes/_connected-apps.md
source/includes/_payouts.md
source/includes/reference/_app_webhooks.md
source/includes/reference/_borderless.md
source/includes/reference/_transfers.md
source/includes/reference/_users.md
source/includes/reference/_webhooks_v1.md

Marked all instances of quoteUuid to be text rather than UUID format.

Replaced all instances of UUID

---

source/includes/_openbanking.md

Add Open Banking API Docs for Direct Debit support

[UK-1293] Add Open Banking API Docs for Direct Debit support
